-- SETANDO O HORÁRIO CORRETINHO -----
ALTER SESSION SET NLS_TIMESTAMP_FORMAT='DD-MON-YY HH24:MI';
/
-- CRIANDO SEQUÊNCIA PRA ID DE DESCONTO -----
CREATE SEQUENCE id INCREMENT by 1 START WITH 1;
/

-- CLIENTE
-- FUNCIONARIO
-- VEICULO
-- DESCONTO
-- CANCELA
-- PEDAGIO
-- MONITORA
-- PAGAMENTO